Repository blablacar/ui-library, pull requests merged in 2018-06, with the labels that each got.

#12 Add props to Autocomplete + handle disabled state on Textfield
  src/autoComplete/index.tsx
  src/autoComplete/index.unit.tsx
  src/autoComplete/story.tsx
  src/textField/index.tsx
  src/textField/style.ts
Labels: enhancement

#13 Update fillRule attribute
  CHANGELOG.md
  src/icon/doubleArrowIcon.tsx
Labels: bug

#18 Pass down the bodyClassName to the AutoCompleteList
  CHANGELOG.md
  src/autoComplete/index.tsx
Labels: enhancement

#21 [BBCSPA-1446] Checkbox position change and more
  CHANGELOG.md
  src/checkbox/__snapshots__/index.unit.tsx.snap
  src/checkbox/index.tsx
  src/checkbox/index.unit.tsx
  src/checkbox/story.tsx
  src/checkbox/style.ts
Labels: enhancement

#22 Set up array to display places in the Itinerary
  CHANGELOG.md
  src/itinerary/__snapshots__/index.unit.tsx.snap
  src/itinerary/index.tsx
  src/itinerary/index.unit.tsx
  src/itinerary/story.tsx
  src/itinerary/style.ts
  src/tripCard/index.tsx
  src/tripCard/index.unit.tsx
  src/tripCard/story.tsx
Labels: enhancement

#27 [BBCSPA-1467] Update dependencies & fix tslint
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/autoComplete/autoCompleteList.unit.tsx
  src/autoComplete/index.tsx
  src/autoComplete/index.unit.tsx
  src/autoComplete/story.tsx
  src/button/index.tsx
  src/button/story.tsx
  src/checkbox/__snapshots__/index.unit.tsx.snap
  src/datePicker/theme.ts
  src/icon/story.tsx
  src/stars/story.tsx
  src/stepper/index.unit.tsx
  tslint.json
Labels: bug, enhancement

#28 [BBCSPA-1550] Remove the margin around the profile
  src/profile/style.ts
Labels: bug

#26 [BBCSPA-1507] Improve the kirk icons management
  CHANGELOG.md
  bin/templates/icon.tsx
  package-lock.json
  package.json
  src/_utils/story.tsx
  src/autoComplete/autoCompleteList.tsx
  src/autoComplete/index.tsx
  src/autoComplete/story.tsx
  src/autoComplete/style.ts
  src/button/index.tsx
  src/button/story.tsx
  src/icon/arrowIcon.tsx
  src/icon/checkIcon.tsx
  src/icon/chevronIcon.tsx
  src/icon/circleIcon.tsx
  src/icon/clockIcon.tsx
  src/icon/comfortIcon.tsx
  src/icon/crossIcon.tsx
  src/icon/crosshairIcon.tsx
  src/icon/decreaseIcon.tsx
  src/icon/doubleArrowIcon.tsx
  src/icon/eyeIcon.tsx
  src/icon/facebookIcon.tsx
  src/icon/increaseIcon.tsx
  src/icon/instagramIcon.tsx
  src/icon/ladyIcon.tsx
  src/icon/lightningIcon.tsx
  src/icon/pinIcon.tsx
  src/icon/proximityIcon.tsx
  src/icon/questionIcon.tsx
  src/icon/searchIcon.tsx
  src/icon/starIcon.tsx
  src/icon/story.tsx
  src/icon/trashIcon.tsx
  src/icon/twitterIcon.tsx
  src/icon/vkontakteIcon.tsx
  src/icon/youtubeIcon.tsx
  src/index.tsx
  src/itemChoice/index.tsx
  src/itemChoice/story.tsx
  src/loader/index.tsx
  src/loader/style.ts
  src/menu/menuItem.tsx
  src/message/story.tsx
  src/profile/index.tsx
  src/pushInfo/index.tsx
  src/radio/style.ts
  src/radioGroup/story.tsx
  src/stars/style.ts
  src/title/story.tsx
  src/transitions/index.tsx
  src/tripCard/index.tsx
  src/uneditableTextField/index.tsx
  src/why/index.tsx
  src/why/story.tsx
  src/why/style.ts
  tsconfig.json
  tslint.json
Labels: enhancement
