Repository blablacar/ui-library, pull requests merged in 2020-03, with the labels that each got.

#581 Add aria label to ItemInfo, and aria-hidden to Item
  CHANGELOG.md
  src/itemInfo/index.tsx
  src/itemInfo/story.tsx
Labels: enhancement

#571 [BBC-1272] Define Typography Components on top of `Text`
  .storybook/config.js
  CHANGELOG.md
  package-lock.json
  src/index.unit.tsx
  src/typography/Text.tsx
  src/typography/body/index.tsx
  src/typography/body/story.tsx
  src/typography/bodyStrong/index.tsx
  src/typography/bodyStrong/story.tsx
  src/typography/caption/index.tsx
  src/typography/caption/story.tsx
  src/typography/display1/index.tsx
  src/typography/display1/story.tsx
  src/typography/display2/index.tsx
  src/typography/display2/story.tsx
  src/typography/index.tsx
  src/typography/specifications/typography.md
  src/typography/story.tsx
  src/typography/subHeader/index.tsx
  src/typography/subHeader/story.tsx
  src/typography/subHeaderStrong/index.tsx
  src/typography/subHeaderStrong/story.tsx
  src/typography/title/index.tsx
  src/typography/title/story.tsx
  src/typography/titleStrong/index.tsx
  src/typography/titleStrong/story.tsx
  stories/index.tsx
Labels: good first issue, question

#636 [BBC-7350] Update icons import
  CHANGELOG.md
  src/drawer/story.tsx
  src/layout/section/columnedContentSection/story.tsx
  src/menu/story.tsx
  src/pages/ridedetails/carpool.story.tsx
  src/pages/searchResults/tabs.story.tsx
  src/pages/yourrides/history.story.tsx
  src/pages/yourrides/rides.story.tsx
Labels: good first issue
